### ISSUE TITLE
How to declare a class in pure javaScript?

### ISSUE THREAD

**Issue by victorteokw** [cheunghy/CocoaBean#2]
What's your opinion? 

May use a way that is similar to [Backbone](http://backbonejs.org)?

Some other ways?

**Comment by nightire** [comment]
Why not involve with ES6 (ES2015 now), native support for class syntax

**Comment by victorteokw** [comment]
@nightire I remember there is a tool to compile ES6 into ES5. What's the name and is it easy to setup?

**Comment by nightire** [comment]
@cheunghy There're bunch of project can make it happen, my personal recommendation is [Babel](https://github.com/babel), very easy to setup and use, just a pure node module, you can use it as a command or in node script.

**Comment by victorteokw** [comment]
I found this: https://github.com/babel/ruby-babel-transpiler
Officially supported by babel.

Indeed, ES6 syntax will be support by CocoaBean.

How about user just wants to write ES5?

**Comment by nightire** [comment]
ES6 is superset of ES5, it doesn't prevent user write valid ES5 codes, except lacks of some new features that ONLY provided ES6. For example, the `Class` syntax is just a sugar layer implements the prototype based OO system, users can still write equivalent ES5 codes to archive these.

BTW, by using Babel, you can easily translate ES6 to ES5, so basically it still runs with ES5 codes for now.

**Comment by victorteokw** [comment]
@nightire Thanks. 

So the answer comes out:
User declare a javaScript class in ES6.
And CocoaBean will convert when generating target application js file.
